import { CdkDragStart, CdkDropList, moveItemInArray } from '@angular/cdk/drag-drop';
import { Component, OnInit } from '@angular/core';

export interface PeriodicElement {
  name: string;
  position: number;
  density: number;
  weight: number;
  symbol: string;
  source: string;
  inputType:string;
}

const ELEMENT_DATA: PeriodicElement[] = [{
	"name": "Hydrogen",
	"weight": 1.008,
	"density": 0.08988,
	"position": 1,
	"symbol": "H",
	"source": "https://en.wikipedia.org/wiki/Hydrogen",
	"inputType": "radio"
}, {
	"name": "Helium",
	"weight": 4.0026022,
	"density": 0.1786,
	"position": 2,
	"symbol": "He",
	"source": "https://en.wikipedia.org/wiki/Helium",
	"inputType": "checkbox"
}, {
	"name": "Lithium",
	"weight": 6.94,
	"density": 0.534,
	"position": 3,
	"symbol": "Li",
	"source": "https://en.wikipedia.org/wiki/Lithium",
	"inputType": "input"
}, {
	"name": "Beryllium",
	"weight": 9.01218315,
	"density": 1.85,
	"position": 4,
	"symbol": "Be",
	"source": "https://en.wikipedia.org/wiki/Beryllium",
	"inputType": "radio"
}, {
	"name": "Boron",
	"weight": 10.81,
	"density": 2.08,
	"position": 5,
	"symbol": "B",
	"source": "https://en.wikipedia.org/wiki/Boron",
	"inputType": "radio"
}, {
	"name": "Carbon",
	"weight": 12.011,
	"density": 1.821,
	"position": 6,
	"symbol": "C",
	"source": "https://en.wikipedia.org/wiki/Carbon",
	"inputType": "checkbox"
}, {
	"name": "Nitrogen",
	"weight": 14.007,
	"density": 1.251,
	"position": 7,
	"symbol": "N",
	"source": "https://en.wikipedia.org/wiki/Nitrogen",
	"inputType": "checkbox"
}, {
	"name": "Oxygen",
	"weight": 15.999,
	"density": 1.429,
	"position": 8,
	"symbol": "O",
	"source": "https://en.wikipedia.org/wiki/Oxygen",
	"inputType": "textArea"
}, {
	"name": "Fluorine",
	"weight": 18.9984031636,
	"density": 1.696,
	"position": 9,
	"symbol": "F",
	"source": "https://en.wikipedia.org/wiki/Fluorine",
	"inputType": "checkbox"
}, {
	"name": "Neon",
	"weight": 20.17976,
	"density": 0.9002,
	"position": 10,
	"symbol": "Ne",
	"source": "https://en.wikipedia.org/wiki/Neon",
	"inputType": "textArea"
}, {
	"name": "Sodium",
	"weight": 22.989769282,
	"density": 0.968,
	"position": 11,
	"symbol": "Na",
	"source": "https://en.wikipedia.org/wiki/Sodium",
	"inputType": "input"
}, {
	"name": "Magnesium",
	"weight": 24.305,
	"density": 1.738,
	"position": 12,
	"symbol": "Mg",
	"source": "https://en.wikipedia.org/wiki/Magnesium",
	"inputType": "radio"
}, {
	"name": "Aluminium",
	"weight": 26.98153857,
	"density": 2.7,
	"position": 13,
	"symbol": "Al",
	"source": "https://en.wikipedia.org/wiki/Aluminium",
	"inputType": "textArea"
}, {
	"name": "Silicon",
	"weight": 28.085,
	"density": 2.329,
	"position": 14,
	"symbol": "Si",
	"source": "https://en.wikipedia.org/wiki/Silicon",
	"inputType": "input"
}, {
	"name": "Phosphorus",
	"weight": 30.9737619985,
	"density": 1.823,
	"position": 15,
	"symbol": "P",
	"source": "https://en.wikipedia.org/wiki/Phosphorus",
	"inputType": "radio"
}, {
	"name": "Sulfur",
	"weight": 32.06,
	"density": 2.07,
	"position": 16,
	"symbol": "S",
	"source": "https://en.wikipedia.org/wiki/Sulfur",
	"inputType": "radio"
}, {
	"name": "Chlorine",
	"weight": 35.45,
	"density": 3.2,
	"position": 17,
	"symbol": "Cl",
	"source": "https://en.wikipedia.org/wiki/Chlorine",
	"inputType": "textArea"
}, {
	"name": "Argon",
	"weight": 39.9481,
	"density": 1.784,
	"position": 18,
	"symbol": "Ar",
	"source": "https://en.wikipedia.org/wiki/Argon",
	"inputType": "radio"
}, {
	"name": "Potassium",
	"weight": 39.09831,
	"density": 0.862,
	"position": 19,
	"symbol": "K",
	"source": "https://en.wikipedia.org/wiki/Potassium",
	"inputType": "radio"
}, {
	"name": "Calcium",
	"weight": 40.0784,
	"density": 1.55,
	"position": 20,
	"symbol": "Ca",
	"source": "https://en.wikipedia.org/wiki/Calcium",
	"inputType": "input"
}, {
	"name": "Scandium",
	"weight": 44.9559085,
	"density": 2.985,
	"position": 21,
	"symbol": "Sc",
	"source": "https://en.wikipedia.org/wiki/Scandium",
	"inputType": "input"
}, {
	"name": "Titanium",
	"weight": 47.8671,
	"density": 4.506,
	"position": 22,
	"symbol": "Ti",
	"source": "https://en.wikipedia.org/wiki/Titanium",
	"inputType": "input"
}, {
	"name": "Vanadium",
	"weight": 50.94151,
	"density": 6,
	"position": 23,
	"symbol": "V",
	"source": "https://en.wikipedia.org/wiki/Vanadium",
	"inputType": "checkbox"
}, {
	"name": "Chromium",
	"weight": 51.99616,
	"density": 7.19,
	"position": 24,
	"symbol": "Cr",
	"source": "https://en.wikipedia.org/wiki/Chromium",
	"inputType": "radio"
}, {
	"name": "Manganese",
	"weight": 54.9380443,
	"density": 7.21,
	"position": 25,
	"symbol": "Mn",
	"source": "https://en.wikipedia.org/wiki/Manganese",
	"inputType": "input"
}, {
	"name": "Iron",
	"weight": 55.8452,
	"density": 7.874,
	"position": 26,
	"symbol": "Fe",
	"source": "https://en.wikipedia.org/wiki/Iron",
	"inputType": "radio"
}, {
	"name": "Cobalt",
	"weight": 58.9331944,
	"density": 8.9,
	"position": 27,
	"symbol": "Co",
	"source": "https://en.wikipedia.org/wiki/Cobalt",
	"inputType": "checkbox"
}, {
	"name": "Nickel",
	"weight": 58.69344,
	"density": 8.908,
	"position": 28,
	"symbol": "Ni",
	"source": "https://en.wikipedia.org/wiki/Nickel",
	"inputType": "input"
}, {
	"name": "Copper",
	"weight": 63.5463,
	"density": 8.96,
	"position": 29,
	"symbol": "Cu",
	"source": "https://en.wikipedia.org/wiki/Copper",
	"inputType": "checkbox"
}, {
	"name": "Zinc",
	"weight": 65.382,
	"density": 7.14,
	"position": 30,
	"symbol": "Zn",
	"source": "https://en.wikipedia.org/wiki/Zinc",
	"inputType": "checkbox"
}, {
	"name": "Gallium",
	"weight": 69.7231,
	"density": 5.91,
	"position": 31,
	"symbol": "Ga",
	"source": "https://en.wikipedia.org/wiki/Gallium",
	"inputType": "radio"
}, {
	"name": "Germanium",
	"weight": 72.6308,
	"density": 5.323,
	"position": 32,
	"symbol": "Ge",
	"source": "https://en.wikipedia.org/wiki/Germanium",
	"inputType": "input"
}, {
	"name": "Arsenic",
	"weight": 74.9215956,
	"density": 5.727,
	"position": 33,
	"symbol": "As",
	"source": "https://en.wikipedia.org/wiki/Arsenic",
	"inputType": "input"
}, {
	"name": "Selenium",
	"weight": 78.9718,
	"density": 4.81,
	"position": 34,
	"symbol": "Se",
	"source": "https://en.wikipedia.org/wiki/Selenium",
	"inputType": "input"
}, {
	"name": "Bromine",
	"weight": 79.904,
	"density": 3.1028,
	"position": 35,
	"symbol": "Br",
	"source": "https://en.wikipedia.org/wiki/Bromine",
	"inputType": "input"
}, {
	"name": "Krypton",
	"weight": 83.7982,
	"density": 3.749,
	"position": 36,
	"symbol": "Kr",
	"source": "https://en.wikipedia.org/wiki/Krypton",
	"inputType": "textArea"
}, {
	"name": "Rubidium",
	"weight": 85.46783,
	"density": 1.532,
	"position": 37,
	"symbol": "Rb",
	"source": "https://en.wikipedia.org/wiki/Rubidium",
	"inputType": "textArea"
}, {
	"name": "Strontium",
	"weight": 87.621,
	"density": 2.64,
	"position": 38,
	"symbol": "Sr",
	"source": "https://en.wikipedia.org/wiki/Strontium",
	"inputType": "input"
}, {
	"name": "Yttrium",
	"weight": 88.905842,
	"density": 4.472,
	"position": 39,
	"symbol": "Y",
	"source": "https://en.wikipedia.org/wiki/Yttrium",
	"inputType": "radio"
}, {
	"name": "Zirconium",
	"weight": 91.2242,
	"density": 6.52,
	"position": 40,
	"symbol": "Zr",
	"source": "https://en.wikipedia.org/wiki/Zirconium",
	"inputType": "textArea"
}, {
	"name": "Niobium",
	"weight": 92.906372,
	"density": 8.57,
	"position": 41,
	"symbol": "Nb",
	"source": "https://en.wikipedia.org/wiki/Niobium",
	"inputType": "radio"
}, {
	"name": "Molybdenum",
	"weight": 95.951,
	"density": 10.28,
	"position": 42,
	"symbol": "Mo",
	"source": "https://en.wikipedia.org/wiki/Molybdenum",
	"inputType": "input"
}, {
	"name": "Technetium",
	"weight": 98,
	"density": 11,
	"position": 43,
	"symbol": "Tc",
	"source": "https://en.wikipedia.org/wiki/Technetium",
	"inputType": "radio"
}, {
	"name": "Ruthenium",
	"weight": 101.072,
	"density": 12.45,
	"position": 44,
	"symbol": "Ru",
	"source": "https://en.wikipedia.org/wiki/Ruthenium",
	"inputType": "textArea"
}, {
	"name": "Rhodium",
	"weight": 102.905502,
	"density": 12.41,
	"position": 45,
	"symbol": "Rh",
	"source": "https://en.wikipedia.org/wiki/Rhodium",
	"inputType": "textArea"
}, {
	"name": "Palladium",
	"weight": 106.421,
	"density": 12.023,
	"position": 46,
	"symbol": "Pd",
	"source": "https://en.wikipedia.org/wiki/Palladium",
	"inputType": "radio"
}, {
	"name": "Silver",
	"weight": 107.86822,
	"density": 10.49,
	"position": 47,
	"symbol": "Ag",
	"source": "https://en.wikipedia.org/wiki/Silver",
	"inputType": "input"
}, {
	"name": "Cadmium",
	"weight": 112.4144,
	"density": 8.65,
	"position": 48,
	"symbol": "Cd",
	"source": "https://en.wikipedia.org/wiki/Cadmium",
	"inputType": "checkbox"
}, {
	"name": "Indium",
	"weight": 114.8181,
	"density": 7.31,
	"position": 49,
	"symbol": "In",
	"source": "https://en.wikipedia.org/wiki/Indium",
	"inputType": "checkbox"
}, {
	"name": "Tin",
	"weight": 118.7107,
	"density": 7.365,
	"position": 50,
	"symbol": "Sn",
	"source": "https://en.wikipedia.org/wiki/Tin",
	"inputType": "input"
}, {
	"name": "Antimony",
	"weight": 121.7601,
	"density": 6.697,
	"position": 51,
	"symbol": "Sb",
	"source": "https://en.wikipedia.org/wiki/Antimony",
	"inputType": "input"
}, {
	"name": "Tellurium",
	"weight": 127.603,
	"density": 6.24,
	"position": 52,
	"symbol": "Te",
	"source": "https://en.wikipedia.org/wiki/Tellurium",
	"inputType": "checkbox"
}, {
	"name": "Iodine",
	"weight": 126.904473,
	"density": 4.933,
	"position": 53,
	"symbol": "I",
	"source": "https://en.wikipedia.org/wiki/Iodine",
	"inputType": "checkbox"
}, {
	"name": "Xenon",
	"weight": 131.2936,
	"density": 5.894,
	"position": 54,
	"symbol": "Xe",
	"source": "https://en.wikipedia.org/wiki/Xenon",
	"inputType": "textArea"
}, {
	"name": "Cesium",
	"weight": 132.905451966,
	"density": 1.93,
	"position": 55,
	"symbol": "Cs",
	"source": "https://en.wikipedia.org/wiki/Cesium",
	"inputType": "checkbox"
}, {
	"name": "Barium",
	"weight": 137.3277,
	"density": 3.51,
	"position": 56,
	"symbol": "Ba",
	"source": "https://en.wikipedia.org/wiki/Barium",
	"inputType": "checkbox"
}, {
	"name": "Lanthanum",
	"weight": 138.905477,
	"density": 6.162,
	"position": 57,
	"symbol": "La",
	"source": "https://en.wikipedia.org/wiki/Lanthanum",
	"inputType": "input"
}, {
	"name": "Cerium",
	"weight": 140.1161,
	"density": 6.77,
	"position": 58,
	"symbol": "Ce",
	"source": "https://en.wikipedia.org/wiki/Cerium",
	"inputType": "textArea"
}, {
	"name": "Praseodymium",
	"weight": 140.907662,
	"density": 6.77,
	"position": 59,
	"symbol": "Pr",
	"source": "https://en.wikipedia.org/wiki/Praseodymium",
	"inputType": "radio"
}, {
	"name": "Neodymium",
	"weight": 144.2423,
	"density": 7.01,
	"position": 60,
	"symbol": "Nd",
	"source": "https://en.wikipedia.org/wiki/Neodymium",
	"inputType": "checkbox"
}, {
	"name": "Promethium",
	"weight": 145,
	"density": 7.26,
	"position": 61,
	"symbol": "Pm",
	"source": "https://en.wikipedia.org/wiki/Promethium",
	"inputType": "checkbox"
}, {
	"name": "Samarium",
	"weight": 150.362,
	"density": 7.52,
	"position": 62,
	"symbol": "Sm",
	"source": "https://en.wikipedia.org/wiki/Samarium",
	"inputType": "textArea"
}, {
	"name": "Europium",
	"weight": 151.9641,
	"density": 5.264,
	"position": 63,
	"symbol": "Eu",
	"source": "https://en.wikipedia.org/wiki/Europium",
	"inputType": "checkbox"
}, {
	"name": "Gadolinium",
	"weight": 157.253,
	"density": 7.9,
	"position": 64,
	"symbol": "Gd",
	"source": "https://en.wikipedia.org/wiki/Gadolinium",
	"inputType": "radio"
}, {
	"name": "Terbium",
	"weight": 158.925352,
	"density": 8.23,
	"position": 65,
	"symbol": "Tb",
	"source": "https://en.wikipedia.org/wiki/Terbium",
	"inputType": "input"
}, {
	"name": "Dysprosium",
	"weight": 162.5001,
	"density": 8.54,
	"position": 66,
	"symbol": "Dy",
	"source": "https://en.wikipedia.org/wiki/Dysprosium",
	"inputType": "textArea"
}, {
	"name": "Holmium",
	"weight": 164.930332,
	"density": 8.79,
	"position": 67,
	"symbol": "Ho",
	"source": "https://en.wikipedia.org/wiki/Holmium",
	"inputType": "radio"
}, {
	"name": "Erbium",
	"weight": 167.2593,
	"density": 9.066,
	"position": 68,
	"symbol": "Er",
	"source": "https://en.wikipedia.org/wiki/Erbium",
	"inputType": "textArea"
}, {
	"name": "Thulium",
	"weight": 168.934222,
	"density": 9.32,
	"position": 69,
	"symbol": "Tm",
	"source": "https://en.wikipedia.org/wiki/Thulium",
	"inputType": "input"
}, {
	"name": "Ytterbium",
	"weight": 173.0451,
	"density": 6.9,
	"position": 70,
	"symbol": "Yb",
	"source": "https://en.wikipedia.org/wiki/Ytterbium",
	"inputType": "textArea"
}, {
	"name": "Lutetium",
	"weight": 174.96681,
	"density": 9.841,
	"position": 71,
	"symbol": "Lu",
	"source": "https://en.wikipedia.org/wiki/Lutetium",
	"inputType": "input"
}, {
	"name": "Hafnium",
	"weight": 178.492,
	"density": 13.31,
	"position": 72,
	"symbol": "Hf",
	"source": "https://en.wikipedia.org/wiki/Hafnium",
	"inputType": "textArea"
}, {
	"name": "Tantalum",
	"weight": 180.947882,
	"density": 16.69,
	"position": 73,
	"symbol": "Ta",
	"source": "https://en.wikipedia.org/wiki/Tantalum",
	"inputType": "checkbox"
}, {
	"name": "Tungsten",
	"weight": 183.841,
	"density": 19.25,
	"position": 74,
	"symbol": "W",
	"source": "https://en.wikipedia.org/wiki/Tungsten",
	"inputType": "radio"
}, {
	"name": "Rhenium",
	"weight": 186.2071,
	"density": 21.02,
	"position": 75,
	"symbol": "Re",
	"source": "https://en.wikipedia.org/wiki/Rhenium",
	"inputType": "textArea"
}, {
	"name": "Osmium",
	"weight": 190.233,
	"density": 22.59,
	"position": 76,
	"symbol": "Os",
	"source": "https://en.wikipedia.org/wiki/Osmium",
	"inputType": "textArea"
}, {
	"name": "Iridium",
	"weight": 192.2173,
	"density": 22.56,
	"position": 77,
	"symbol": "Ir",
	"source": "https://en.wikipedia.org/wiki/Iridium",
	"inputType": "textArea"
}, {
	"name": "Platinum",
	"weight": 195.0849,
	"density": 21.45,
	"position": 78,
	"symbol": "Pt",
	"source": "https://en.wikipedia.org/wiki/Platinum",
	"inputType": "radio"
}, {
	"name": "Gold",
	"weight": 196.9665695,
	"density": 19.3,
	"position": 79,
	"symbol": "Au",
	"source": "https://en.wikipedia.org/wiki/Gold",
	"inputType": "input"
}, {
	"name": "Mercury",
	"weight": 200.5923,
	"density": 13.534,
	"position": 80,
	"symbol": "Hg",
	"source": "https://en.wikipedia.org/wiki/Mercury (Element)",
	"inputType": "textArea"
}, {
	"name": "Thallium",
	"weight": 204.38,
	"density": 11.85,
	"position": 81,
	"symbol": "Tl",
	"source": "https://en.wikipedia.org/wiki/Thallium",
	"inputType": "checkbox"
}, {
	"name": "Lead",
	"weight": 207.21,
	"density": 11.34,
	"position": 82,
	"symbol": "Pb",
	"source": "https://en.wikipedia.org/wiki/Lead_(element)",
	"inputType": "checkbox"
}, {
	"name": "Bismuth",
	"weight": 208.980401,
	"density": 9.78,
	"position": 83,
	"symbol": "Bi",
	"source": "https://en.wikipedia.org/wiki/Bismuth",
	"inputType": "input"
}, {
	"name": "Polonium",
	"weight": 209,
	"density": 9.196,
	"position": 84,
	"symbol": "Po",
	"source": "https://en.wikipedia.org/wiki/Polonium",
	"inputType": "input"
}, {
	"name": "Astatine",
	"weight": 210,
	"density": 6.35,
	"position": 85,
	"symbol": "At",
	"source": "https://en.wikipedia.org/wiki/Astatine",
	"inputType": "checkbox"
}, {
	"name": "Radon",
	"weight": 222,
	"density": 9.73,
	"position": 86,
	"symbol": "Rn",
	"source": "https://en.wikipedia.org/wiki/Radon",
	"inputType": "input"
}, {
	"name": "Francium",
	"weight": 223,
	"density": 1.87,
	"position": 87,
	"symbol": "Fr",
	"source": "https://en.wikipedia.org/wiki/Francium",
	"inputType": "checkbox"
}, {
	"name": "Radium",
	"weight": 226,
	"density": 5.5,
	"position": 88,
	"symbol": "Ra",
	"source": "https://en.wikipedia.org/wiki/Radium",
	"inputType": "input"
}, {
	"name": "Actinium",
	"weight": 227,
	"density": 10,
	"position": 89,
	"symbol": "Ac",
	"source": "https://en.wikipedia.org/wiki/Actinium",
	"inputType": "radio"
}, {
	"name": "Thorium",
	"weight": 232.03774,
	"density": 11.724,
	"position": 90,
	"symbol": "Th",
	"source": "https://en.wikipedia.org/wiki/Thorium",
	"inputType": "textArea"
}, {
	"name": "Protactinium",
	"weight": 231.035882,
	"density": 15.37,
	"position": 91,
	"symbol": "Pa",
	"source": "https://en.wikipedia.org/wiki/Protactinium",
	"inputType": "checkbox"
}, {
	"name": "Uranium",
	"weight": 238.028913,
	"density": 19.1,
	"position": 92,
	"symbol": "U",
	"source": "https://en.wikipedia.org/wiki/Uranium",
	"inputType": "checkbox"
}, {
	"name": "Neptunium",
	"weight": 237,
	"density": 20.45,
	"position": 93,
	"symbol": "Np",
	"source": "https://en.wikipedia.org/wiki/Neptunium",
	"inputType": "textArea"
}, {
	"name": "Plutonium",
	"weight": 244,
	"density": 19.816,
	"position": 94,
	"symbol": "Pu",
	"source": "https://en.wikipedia.org/wiki/Plutonium",
	"inputType": "checkbox"
}, {
	"name": "Americium",
	"weight": 243,
	"density": 12,
	"position": 95,
	"symbol": "Am",
	"source": "https://en.wikipedia.org/wiki/Americium",
	"inputType": "radio"
}, {
	"name": "Curium",
	"weight": 247,
	"density": 13.51,
	"position": 96,
	"symbol": "Cm",
	"source": "https://en.wikipedia.org/wiki/Curium",
	"inputType": "input"
}, {
	"name": "Berkelium",
	"weight": 247,
	"density": 14.78,
	"position": 97,
	"symbol": "Bk",
	"source": "https://en.wikipedia.org/wiki/Berkelium",
	"inputType": "radio"
}, {
	"name": "Californium",
	"weight": 251,
	"density": 15.1,
	"position": 98,
	"symbol": "Cf",
	"source": "https://en.wikipedia.org/wiki/Californium",
	"inputType": "input"
}, {
	"name": "Einsteinium",
	"weight": 252,
	"density": 8.84,
	"position": 99,
	"symbol": "Es",
	"source": "https://en.wikipedia.org/wiki/Einsteinium",
	"inputType": "radio"
}, {
	"name": "Fermium",
	"weight": 257,
	"density": null,
	"position": 100,
	"symbol": "Fm",
	"source": "https://en.wikipedia.org/wiki/Fermium",
	"inputType": "checkbox"
}];



@Component({
  selector: 'app-root',
  styleUrls: ['./app.component.scss'],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  title = 'Material Table column drag and drop';

  columns: any[] = [
    {field: 'inputType'},
    { field: 'position' },
    { field: 'name' },
    { field: 'weight' },
    {field: 'density'},
    { field: 'symbol' },
    {field: 'source'}
  ];
  displayedColumns: string[] = [];
  dataSource = ELEMENT_DATA;

  previousIndex: number;

  ngOnInit() {
    this.setDisplayedColumns();
  }

  setDisplayedColumns() {
    this.columns.forEach(( colunm, index) => {
      colunm.index = index;
      this.displayedColumns[index] = colunm.field;
    });
  }

  dragStarted(event: CdkDragStart, index: number ) {
    this.previousIndex = index;
  }

  dropListDropped(event: CdkDropList, index: number) {
    if (event) {
      moveItemInArray(this.columns, this.previousIndex, index);
      this.setDisplayedColumns();
    }
  }

  addColumn() {
    const randomColumn = Math.floor(Math.random() * this.displayedColumns.length);
    this.displayedColumns.push(this.displayedColumns[randomColumn]);
    this.setDisplayedColumns();
  }

  removeColumn() {
    if (this.displayedColumns.length) {
      this.displayedColumns.pop();
    }
  }
}

